### ISSUE TITLE
File system benchmarking with SBK-GEM

### ISSUE THREAD

**Issue by kmgowda** [kmgowda/SBK#302]
**Describe the Issue (Bug/Feature)**
Run sbk-gem command on set of nodes/systems for file system benchmarking

**To Reproduce**
1. set the ssh name and password on set of host/nodes/systems
2. run the sbk-gem with "-class file" to get the file system benchmarking on all the hosts and integrated on host

**Expected behavior**
you will get the fully integrated file system benchmarking results on the node where you are running sbk-gem

**Additional context**
see the examples here : https://github.com/kmgowda/SBK/tree/master/sbk-gem

**Comment by Amartya-Mahato** [comment]
Hi, Sir
i am trying to reproduce the bug ( i am not sure if i am doing it right )
```
./sbk-gem/build/install/sbk-gem/bin/sbk-gem -class jdbc -readers 1 -size 100 -time ns -seconds 60 -gemuser root -gempass roots -sbkdir build/install/sbk
```

i am facing this error Please guide me with this problem 
```
2022-03-04 22:38:35 INFO SBK-GEM: Ssh Connection to host 'localhost' starting...
2022-03-04 22:38:35 INFO Using MinaServiceFactoryFactory
2022-03-04 22:38:36 ERROR SBK-GEM: Ssh Connection to host 'localhost' time out!
2022-03-04 22:38:36 INFO SBK-GEM: Ssh session establishment Success..
java.net.ConnectException: ssh session to host: localhost not found!
        at io.sbk.gem.impl.SbkSsh.getSession(SbkSsh.java:62)
        at io.sbk.gem.impl.SbkSsh.runCommandAsync(SbkSsh.java:70)
        at io.sbk.gem.impl.SbkGemBenchmark.start(SbkGemBenchmark.java:139)
        at io.sbk.gem.impl.SbkGem.run(SbkGem.java:85)
        at io.sbk.main.SbkGemMain.main(SbkGemMain.java:25)

```

**Comment by kmgowda** [comment]
@Amartya-Mahato  there are could be two problems here

- check if  the ssh login is enabled in  the system where SBK is running
- check the ssh user name and password '-gemuser root -gempass roots' are correct
-

**Comment by Amartya-Mahato** [comment]
@kmgowda Hi sir, I was using __mysql database__ that time, Which was using ___( Standard TCP/IP )___ connection, well i tried to switch the connection to ___( Standard TCP/IP  Over SSH )___ but it was failure too, i am still getting that __error__, is there any other way to reproduce the __actual bug__. 😅😅

**Comment by kmgowda** [comment]
@Amartya-Mahato  the mysql database and sbk-gem command are not related.  
your localhost should have the ssh service running ;
the login id and password of the ssh service should be given with options  -gemuser  and -gempass.
